## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.arange(10)

In [3]:
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.array([1, 2, 4, 6, 10, 2, 6])

In [5]:
arr[arr.argmax()] = 0
print(arr)

[1 2 4 6 0 2 6]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [6]:
from itertools import product

arr = ([1, 2, 3], [4, 5, 6])

In [7]:
arrays = (np.asarray(a) for a in arr)
result = list(product(*arrays))
print(result)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
arr1 = np.array([[1, 2, 3],
               [3, 4, 5],
               [5, 6, 7],
               [7, 8, 9],
               [9, 8, 7],
               [4, 2, 3],
               [5, 8, 3],
               [7, 2, 4]])

arr2 = np.array([[1, 2],
                 [3, 4]])

In [9]:
arr_bool = np.isin(arr1, arr2).all(axis=1)
result_arr = arr1[arr_bool]
print(result_arr)

[[1 2 3]
 [4 2 3]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [10]:
arr = np.array([[0, 2, 4],
              [3, 0, 1],
              [3, 2, 2],
              [3, 1, 0],
              [2, 3, 3],
              [4, 4, 4],
              [3, 1, 0],
              [3, 3, 3],
              [3, 3, 3],
              [1, 1, 1]])

In [11]:
condition = np.logical_and.reduce(arr[:,1:] == arr[:,:-1], axis=1)
result_arr = arr[~condition]
print(result_arr)

[[0 2 4]
 [3 0 1]
 [3 2 2]
 [3 1 0]
 [2 3 3]
 [3 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [12]:
arr = np.array([[0, 2],
              [2, 3],
              [4, 4],
              [3, 1],
              [3, 3],
              [3, 3],
              [1, 1]])

In [13]:
result_arr = np.unique(arr, axis=0)
print(result_arr)

[[0 2]
 [1 1]
 [2 3]
 [3 1]
 [3 3]
 [4 4]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [48]:
X = np.array([[1, 0, 1], 
              [2, 0, 2], 
              [3, 0, 3], 
              [4, 4, 4]])

In [52]:
answer = 1
for ind, x in enumerate(X):
    if ind < len(x) and x[ind]:
        answer *= x[ind]

print(answer)

3


In [53]:
np.prod(np.diag(X)[np.diag(X)!=0])

3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [54]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2]) 

In [55]:
x, y = sorted(x), sorted(y)
print(x == y)

True


In [56]:
np.array_equal(x, y)

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [57]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [59]:
zero_list = []
for ind, el in enumerate(x):
    if ind and not x[ind-1]:
        zero_list.append(el)
print(max(zero_list))

5


In [60]:
zero_index = (np.where(x==0)[0] + 1)[0:-1]
zero_array = np.array(x)[zero_index]
print(np.max(zero_array))

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [61]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

In [62]:
#вариант 1
values_count = {}
for el in x:
    values_count[el] = values_count.get(el, 0) + 1
values, counts = values_count.keys(), values_count.values()
print(values, counts)

#вариант 2
from collections import Counter
values_count = Counter(x)
values, counts = values_count.keys(), values_count.values()
print(values, counts)

dict_keys([2, 3, 5]) dict_values([3, 3, 1])
dict_keys([2, 3, 5]) dict_values([3, 3, 1])


In [64]:
values, counts = np.unique(x, return_counts=True)
print(values, counts)

[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [65]:
from time import time
from math import sqrt
from scipy.spatial.distance import cdist

X = np.array([0, 10, 20, 30])
Y = np.array([0, 100, 200, 300])

In [68]:
start_time = time()

condition = lambda p1, p2: sqrt(((p1-p2)**2).sum())
matrix_answer = np.asarray([[condition(p1, p2) for p2 in X] for p1 in Y])
print(matrix_answer)

print('Execution time:', time() - start_time)

[[  0.  10.  20.  30.]
 [100.  90.  80.  70.]
 [200. 190. 180. 170.]
 [300. 290. 280. 270.]]
Execution time: 0.0009021759033203125


In [69]:
start_time = time()

x_coord, y_coord = np.meshgrid(X, Y)
matrix_answer = abs(x_coord-y_coord)
print(out)

print('Execution time:', time() - start_time)

[[  0  10  20  30]
 [100  90  80  70]
 [200 190 180 170]
 [300 290 280 270]]
Execution time: 0.0005118846893310547


In [28]:
start_time = time()

matrix_answer = cdist(X, Y)
print(matrix_answer)

print('Execution time:', time() - start_time)

ValueError: XA must be a 2-dimensional array.

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [29]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [30]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [31]:
average_calories = np.average(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [32]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [33]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [34]:
np.percentile(calorie_stats, [0, 3.29, 50, 75, 100])
nth_percentile = 3.29

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [35]:
uniques, counts = np.unique(calorie_stats, return_counts=True)
uniques_60 = np.where(uniques>60)[0]
counts_60 = np.array(counts)[uniques_60]
more_calories = counts_60.sum()/counts.sum() * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [36]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [37]:
"""
Было расчитано среднее значение калорийности хлопьев у конкуренотов (106 калорий), 
что значительно превышает этот показатель, по нашей марке (больше на 46 калорий).

Была найдена медиана, которая показывает, что по крайней мере половина значений конкурентов составляет более 100 калорий.
Также был найден процентиль конкурентов с более высоким содержанием калорий, чем среднее по нашей марке, (3.29) 
и расчитано процентное соотношение хлопьев конкурентов с более высоким содержанием калорий (96.1%). 
Результаты говорят о том, что большая часть конкурентов производит хлопья более калорийные, чем у нас.

Также выяснили, что в среднем показатели калорийности хлопьев конкурентов отклоняются от среднего на 19,35 калорий, 
что значительно превышает средний показатель 106 калорий и говорит о высокой изменчивости данных 
и недостаточной точности среднего по этой выборке (нужно увеличить количество наблюдений).

Исходя из этого можно сделать вывод, что необходимо провести более тщательный анализ 
калорийности хлопьев у конкурентов и, если показатели подтвердятся,
то низкую калорийность хлопьев нашей марки можно использовать как конкурентное преимущество
и учитывать при проведении маркетинговой кампании.
"""

'\nБыло расчитано среднее значение калорийности хлопьев у конкуренотов (106 калорий), \nчто значительно превышает этот показатель, по нашей марке (больше на 46 калорий).\nБыла найдена медиана, которая показывает, что по крайней мере половина значений конкурентов составляет более 100 калорий.\nТакже были расчитаны процентиль конкурентов с более высоким содержанием калорий, чем среднее по нашей марке, (3.29) \nи процентное соотношение хлопьев конкурентов с более высоким содержанием калорий (96.1%). \nРезультаты говорят о том, что большая часть конкурентов производит хлопья более калорийные, чем у нас.\nТакже выяснили, что в среднем показатели калорийности хлопьев конкурентов отклоняются от среднего на 19,35 калорий, \nчто значительно превышает средний показатель 106 калорий и говорит о высокой изменчивости данных \nи недостаточной точности среднего по этой выборке (нужно увеличить количество наблюдений)\n\nИсходя из этого можно сделать вывод, что необходимо провести более тщательный анал